substitutions:
  device_name: switch
  mqtt_broker: 10.10.10.10
  ap_ssid: "IOT"
  ap_pass: "xmsn02b1"

# WF30 - Eva Logik 3-Way Switch
# https://templates.blakadder.com/evalogik_WF30.html
esphome:
  platform: ESP8266
  board: esp01_1m
  name: ${device_name}
  esp8266_restore_from_flash: true

# Configure WiFi
wifi:
  ssid: ${ap_ssid}
  password: ${ap_pass}
  ap: # Enable fallback hotspot in case wifi connection fails
    ssid: "ESPHome"

# Enable native API
api:
  reboot_timeout: 0s

# Enable captive portal in case wifi connection fails
captive_portal:

# Enable debug output
debug:

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # Disable logging to serial

# Enable MQTT
mqtt:
  broker: ${mqtt_broker}
  topic_prefix: esphome/${device_name}
  discovery: False

# Enable OTA updates
ota:

# Define switches/relays
switch:
  - platform: restart
    name: "Restart"
  - platform: gpio
    id: relay
    name: "Relay"
    pin: GPIO12

# Provides basic web interface and firmware upload capability
web_server:
  port: 80

# Define sensors
binary_sensor:
  - platform: gpio
    id: button_top
    pin:
      number: GPIO13
      inverted: True
    on_multi_click:
      # Single Push
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.3s
        then:
          if:
            condition:
              mqtt.connected:
            then:
              - text_sensor.template.publish:
                  id: top_state
                  state: "SINGLE"
            else:
              - switch.turn_on: relay
      # Double Push
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - text_sensor.template.publish:
              id: top_state
              state: "DOUBLE"
      # Triple Push
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - switch.turn_on: relay
      # Single Long Press
      - timing:
          - ON for 0.5s to 1.5s
          - OFF for at least 0.3s
        then:
          - text_sensor.template.publish:
              id: top_state
              state: "LONG"
      # Press and Hold
      - timing:
          - ON for at least 1.7s
        then:
          - text_sensor.template.publish:
              id: top_state
              state: "HOLD"
      - timing:
          - OFF for at least 0.4s
        then:
          if:
            condition:
              text_sensor.state:
                id: top_state
                state: "HOLD"
            then:
              - text_sensor.template.publish:
                  id: top_state
                  state: "RELEASE"

  - platform: gpio
    id: button_bottom
    pin:
      number: GPIO4
      inverted: True
    on_multi_click:
      # Single Push
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.3s
        then:
          if:
            condition:
              mqtt.connected:
            then:
              - text_sensor.template.publish:
                  id: bottom_state
                  state: "SINGLE"
            else:
              - switch.turn_off: relay
      # Double Push
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - text_sensor.template.publish:
              id: bottom_state
              state: "DOUBLE"
      # Triple Push
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at most 0.5s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - switch.turn_off: relay
      # Long Press
      - timing:
          - ON for 0.5s to 1.5s
          - OFF for at least 0.3s
        then:
          - text_sensor.template.publish:
              id: bottom_state
              state: "LONG"
      # Push and Hold
      - timing:
          - ON for at least 1.7s
        then:
          - text_sensor.template.publish:
              id: bottom_state
              state: "HOLD"
      - timing:
          - OFF for at least 0.4s
        then:
          if:
            condition:
              text_sensor.state:
                id: bottom_state
                state: "HOLD"
            then:
              - text_sensor.template.publish:
                  id: bottom_state
                  state: "RELEASE"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    unit_of_measurement: "%"
    update_interval: 30s
    filters:
      - lambda: return 2.0 * (x + 100.0);
      - delta: 5

text_sensor:
  - platform: template
    id: top_state
    name: "Button1"
  - platform: template
    id: bottom_state
    name: "Button2"
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    mac_address:
      name: "MAC Address"
